### ISSUE TITLE
Support for arrays, sums, products

### ISSUE THREAD

**Issue by russellromney** [wangronin/MIP-EGO#1]
This is a really cool project! Especially with regards to utilising GPU for parallel computation. 

I'd love to see support for constraints i.e. sum, product of variable arrays. If that's not on your road map, do you know of any other projects/packages that implement MIP on GPU?

**Comment by Basvanstein** [comment]
Dear russellromney, 

Adding constraints is currently not on the roadmap, but they should not be too hard to implement.
You can switch the MIP optimizer with any optimizer that exists as long as it can handle mixed integer data.
